### ISSUE TITLE
Plotting error after first installation

### ISSUE THREAD

**Issue by cyrilzakka** [openai/spinningup#1]
As a heads up some users might run into the following error when attempting to plot the performance of their agent when checking their installation the first time:

> ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.

In order to overcome this, they can follow the steps outlined [here](https://stackoverflow.com/questions/21784641/installation-issue-with-matplotlib-python) 

I have no clue if this only happens in a virtual environment (I was personally using a Conda environment) and didn't know where else to put it. Hope this helps!

**Comment by machinaut** [comment]
Thanks!  This will probably be useful for other folks that find the same thing.

If there's something more we can do from the package side it'd be good to know that too.

(We ran into this issue during early testing, and its a pretty tricky one to tackle as a python package)

**Comment by jachiam** [comment]
Fixing this within the next couple of days is on the todo list! Thanks for flagging!

**Comment by jachiam** [comment]
Update: suuuuuper sorry for how long a real response on this has gone on. Handling it requires a partial installation doc rewrite which I haven't had time to do yet (because I want to verify that it'll work by tinkering on a mac computer I'm currently away from). Coming soon.

**Comment by cyrilzakka** [comment]
> Update: suuuuuper sorry for how long it's taking to give a real response on this. Handling it requires a partial installation doc rewrite which I haven't had time to do yet (because I want to verify that it'll work by tinkering on a mac computer I'm currently away from). Coming soon.

No worries man, there's really no hurry. A quick Google search should help anyone with a problem, or they can easily refer to the issues section of the repo. Enjoy your vacation! (I take it that's why you're away)

**Comment by zmpster** [comment]
Nevermind, this works now! `conda install matplotlib` basically messed things up more, and then I had to restart from scratch and follow the actual directions in original post. Thanks @cyrilzakka !!

**Comment by Kastier1** [comment]
Facing same problem using mkvirtualenv for my virtualenv

**Comment by JiamingXiao** [comment]
> Nevermind, this works now! `conda install matplotlib` basically messed things up more, and then I had to restart from scratch and follow the actual directions in original post. Thanks @cyrilzakka !!

Hi, would you mind tell me how did you fix the  'NSInvalidArgumentException'  problem? I got the same problem, and no idea how to fix it. Thanks.

**Comment by jachiam** [comment]
So, at long last, to the best of my knowledge this issue is fixed by upgrading the matplotlib install to version 3.1.1. The `setup.py` file now requires this. I'm going to mark this closed for now. :)
