### ISSUE TITLE
The installation link for Mujoco points to a wrong location

### ISSUE THREAD

**Issue by rcshubhadeep** [openai/spinningup#10]
The text reads like the following - 

```
First, go to the mujoco-py github page. Follow the installation instructions in the README, 
which describe how to install the MuJoCo physics engine and the mujoco-py 
package (which allows the use of MuJoCo from Python).
```
However, when someone clicks on the link it brings them here - https://github.com/openai/mujoco-py/tree/master/mujoco_py

Whereas I believe it should bring them here - https://github.com/openai/mujoco-py
(Where the readme is)

**Comment by jachiam** [comment]
[Latest commit](https://github.com/openai/spinningup/commit/23cb30c1c03067105cdc955c15f45ecd30a66e57) includes the fix.
