### ISSUE TITLE
PPO StdEpRet is always large

### ISSUE THREAD

**Issue by AchillesJJ** [openai/spinningup#100]
If the `StdEpRet` in PPO algorithm is always very large compared to `AvergeEpRet`, what parameters should I tune ? Does that mean the algorithm not converge well ?

**Comment by jachiam** [comment]
It depends a lot on what environment you're in, and how large AverageEpRet and StdEpRet are. But in most of the Gym environments used in Spinning Up, yes, noisy returns would be a sign you probably haven't converged. What things to tune also depend on the environment, but a good place to start would probably be `steps_per_epoch` (make it bigger) and `epochs` (also make it bigger).
