### ISSUE TITLE
[Question] For SAC, What would be preferable when we have actions with different range?

### ISSUE THREAD

**Issue by hardikmeisheri** [openai/spinningup#102]
Let's say from we have actions in a range of 0-1. Would it make sense to use sigmoid in squashing function and subsequently also the clip the noise distribution? Or it is more preferable to rescale the actions between -1 to 1 for any environment.

**Comment by jachiam** [comment]
Use of sigmoid is fundamentally reasonable, although you'd have to come up with a new expression for the log-prob of the policy after the squash.

**Comment by hardikmeisheri** [comment]
Thanks. Yes, that is tricky, as the clipping itself won't work.

Will wait for a day or two if I get some more suggestions and close this.

**Comment by hardikmeisheri** [comment]
Thanks. Yes, that is tricky, as the clipping itself won't work.

Will wait for a day or two if I get some more suggestions and close this.
