### ISSUE TITLE
RL Intro first video is not playing

### ISSUE THREAD

**Issue by andretadeu** [openai/spinningup#113]
Hi,

Whilst reading the docs, in the **Part 1: Key Concepts in RL**, I noticed that the first video is not playing. Trying to open the video outside the page, I've got the following return:

```
<Error>
<Code>UserProjectAccountProblem</Code>
<Message>User project billing account not in good standing.</Message>
<Details>
The billing account for project 484665841453 is disabled in state absent
</Details>
</Error>
```

It seems it is not exactly a bug, but something must be done to the video being able to play.

Thanks,

André Tadeu de Carvalho

**Comment by jachiam** [comment]
Thanks for the heads-up, will look into this!

**Comment by jachiam** [comment]
Fixed by [latest commit](https://github.com/openai/spinningup/commit/705446c7f4f0407d31a3159ba93c2dec164da2a8).
