### ISSUE TITLE
Feature Request - SAC with Learned Temperature

### ISSUE THREAD

**Issue by RylanSchaeffer** [openai/spinningup#119]
Hi! It looks like the SAC implementation is based on Haarnoja's [original paper](https://arxiv.org/abs/1801.01290) with a fixed temperature parameter, which [he and his collaborators claim](https://arxiv.org/abs/1812.05905) is surpassed by its successor, SAC with a learned temperature parameter. Would it be possible for the SAC API to have a boolean indicating whether the temperature parameter is to be learned? The underlying implementation would need to be changed appropriately.

**Comment by jachiam** [comment]
Hi @RylanSchaeffer! This is on my "to-do" list for the upcoming revisions in April.

**Comment by RylanSchaeffer** [comment]
Great :) Should I close this issue or leave it open?

**Comment by jachiam** [comment]
May as well close it for now---it's unlikely I'll forget this (given that I've already mostly implemented it in my private repo). Thanks for making the request!
