### ISSUE TITLE
MPI Issue

### ISSUE THREAD

**Issue by ruifengma** [openai/spinningup#129]
when running ppo example, this issue raises,
`There are not enough slots available in the system to satisfy the 4 slots
that were requested by the application:
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3

Either request fewer slots for your application, or make more slots available
for use.`

I'm currently using macbook air (2017 model), macOS Mojave, python 3.6

**Comment by jachiam** [comment]
Hi @ruifengma! This is not a bug---what it's saying is that you have less than 4 physical CPU cores and so you can't run 4 parallel processes with one on each core. Set --num_cpu to 2 or 1 instead.
