### ISSUE TITLE
why is reward always 1 even at epoch=0?

### ISSUE THREAD

**Issue by Xunzhaocunzi** [openai/spinningup#130]
![Screenshot from 2019-03-21 12-54-52](https://user-images.githubusercontent.com/32579634/54773922-9b2dcd00-4bd8-11e9-8a0d-3b78504de424.png)

My intuition was that at the beginning of the training there were few reward = 1 and most of rewards should be 0. As the training proceeded, rewards = 1 appeared more and more, which meant the agent gradually learned how to balance the pole on the cart. 

However, the fact was that reward was always 1, considering that at the beginning the actions were purely random. How could the agent learn to control if random actions would get rewards? Could anyone shed some light on it?

**UPDATE:** 
I read the documentation thoroughly, and found reward = 1 was simply set up in that way. Then, my question is if any random actions generate reward = 1, no reward = 0 at all, how can the agent know what actions will maximize the return, since there is no difference between random actions and "correct" actions regarding return? 

Thank you!

**Comment by Tom2718** [comment]
From the cartpole environment description, "A reward of +1 is provided for every timestep that the pole remains upright." Thus your agent will always start with some positive reward, until the pole falls over. The agent will weight the actions (whether random or chosen) that lead to positive reward higher - that's the whole idea of reinforcement learning. Over time this maximizes the return.

**Comment by jachiam** [comment]
Yep, when the pole falls over the episode ends. Since @Tom2718 had the correct answer, I am going to mark this closed. Best of luck in your continued studies @Xunzhaocunzi!
