### ISSUE TITLE
control dependencies of SAC in implementing auto temperature tuning version

### ISSUE THREAD

**Issue by mch5048** [openai/spinningup#136]
Hi, I'm really enjoying the insightful code implementation here!
I'm working on a temperature tuning version of SAC, and it seems working.
While doing so, I become interested in the usage of tf.control_dependencies in SAC 
implementation, which arises me a question that should I use this feature in executing
temperature tuning ops.
According to #45, It seems that following the logical order in pseudo-code of the original EC-SAC paper does not affect the performance. So, In this sense, what's would be the best practice for me to execute alpha-value optimizer in the training sequence?
Thanks in advance!

**Comment by zlw21gxy** [comment]
You can checkout our implication https://github.com/createamind/DRL/tree/master

**Comment by mch5048** [comment]
@zlw21gxy Thanks! It helped a lot!
