### ISSUE TITLE
Are there some problems in the ppo code?

### ISSUE THREAD

**Issue by chaobiubiu** [openai/spinningup#138]
Line 259 in ppo.py, buf.store(o,a,r,v_t,logp_t) 
At the first step in every epoch, we set r=0. So the operation in line 259 results that the first record of reward in the rew_buf is always 0. In fact, we should  record the reward after executing pi in the first state.  
The operation above causes the problems in the function finish_path. In line62 and line 66, the first record in the rew_buf may result some problems and leave out the last reward during the end of every epoch. 
To solve this problems, I change the code slightly as below:
line262: o_, r, d, _=env.step(a[0])
line263: buf.store(o, a, r, v_t, logp_t)
line264: ep_ret+ = r
line265: ep_len+ = 1
line266: o = o_
After changing these codes, I also change:
line 58: rews = self.rew_buf[path_slice]
line 62: deltas=rews + self.gamma * vals[1:] - vals[:-1] 
line 66:self.ret_buf[path_slice] = core.discount_cumsum(rews, self.gamma)

I don't know whether I am wrong. I am sincerely hoping that you can answer my question. Thank you!

**Comment by chaobiubiu** [comment]
In line97: last_val = 0 if d else sess.run(v, feed_dict={x_ph: o.reshape(1, -1)}) 
Because we have record the last reward in the rew_buf, we don't need to set last_val = r

**Comment by alexandervandekleut** [comment]
Furthermore at line 97, shouldn't you take sess.run(v, feed_dict={x_ph: o.reshape(1, -1)})[0] since otherwise it returns a length-1 rank-1 tensor, and not a scalar?

**Comment by alexandervandekleut** [comment]
@chaobiubiu the reward at time T and the value at time T are not the same, because the critic tries to predict V (hence needing to run tensorflow to predict it).

**Comment by chaobiubiu** [comment]
> @chaobiubiu the reward at time T and the value at time T are not the same, because the critic tries to predict V (hence needing to run tensorflow to predict it).

I know it. I still think that there are some problems in the data processing. So I use the ppo2 in the openai baselines

**Comment by jpiabrantes** [comment]
There is a pull-request https://github.com/openai/spinningup/pull/126 to fix this.

**Comment by jachiam** [comment]
Reward shift issue fixed in latest version.
