### ISSUE TITLE
How to use mpi with python script

### ISSUE THREAD

**Issue by AchillesJJ** [openai/spinningup#140]
I try to use ppo algorithm with mpi in a script way as follows
```python
# encoding: utf-8
from spinup import ppo
from spinup.utils.mpi_tools import mpi_fork
import gym

# set env
env = gym.make('LunarLander-v2')
env_fn = lambda: env

mpi_fork(4)

# set parameters for ppo
ac_kwargs = dict(hidden_sizes=[32,32])
output_dir = os.path.join('model', 'OAT_outputs_N500tt')
logger_kwargs = dict(output_dir=output_dir, exp_name='test')
ppo(env_fn=env_fn, ac_kwargs=ac_kwargs, epochs=200,
    logger_kwargs=logger_kwargs, gamma=0.999)
```
Here we choose LunarLander-v2. However, the code given above always crash after a few epochs and the average return per epoch is very small even negative. As a comparison, if we delete `mpi_fork(4)`, then it just works fine. 

Another question is that the results of python script is always worse than that of command line
```shell
python -m spinup.run ppo --hid "[32,32]" --env LunarLander-v2 --exp_name installtest --gamma 0.999
```
even they actually have the same parameters.

So my questions are how to use mpi in a script way and why the results of command line is better.

**Comment by jachiam** [comment]
Hello! Sorry for the very long delay.

I was able to run your script (with `mpi_fork(4)` included) without crashes, so unfortunately I can't reproduce the issue.

```
---------------------------------------
|             Epoch |             199 |
|      AverageEpRet |             -50 |
|          StdEpRet |            34.5 |
|          MaxEpRet |           -13.8 |
|          MinEpRet |            -105 |
|             EpLen |             851 |
|      AverageVVals |           -31.3 |
|          StdVVals |            3.92 |
|          MaxVVals |           -20.7 |
|          MinVVals |           -39.4 |
| TotalEnvInteracts |           8e+05 |
|            LossPi |       -1.49e-08 |
|             LossV |             653 |
|       DeltaLossPi |         -0.0049 |
|        DeltaLossV |           -88.3 |
|           Entropy |           0.759 |
|                KL |         0.00344 |
|          ClipFrac |          0.0443 |
|          StopIter |              79 |
|              Time |             457 |
---------------------------------------
```

As to differences in performance across different runs: this is pretty normal for RL, where there is very high variance in algorithm performance even with all of the parameters the same. Even if you are setting the same random seeds, randomness introduced some other way could cause different results.
