### ISSUE TITLE
How to install without Mujoco

### ISSUE THREAD

**Issue by justindixon** [openai/spinningup#15]
I cannot afford a Mujoco licence and cannot seem to install without it. Is it possible to install without Mujoco dependencies?

**Comment by jachiam** [comment]
Yes, currently working on writing updates to the docs with instructions for this. 

Although in the meanwhile you may want to get a 30-day free trial MuJoCo license if you can---it's fun to play with!

**Comment by justindixon** [comment]
Thanks for that Josh!
