### ISSUE TITLE
Why is the line blurred?

### ISSUE THREAD

**Issue by isaacleeai** [openai/spinningup#151]
Under ["Reward and Return" ](https://spinningup.openai.com/en/latest/spinningup/rl_intro.html), in the "You Should know" box, it says

>While the line between these two formulations of return are quite stark in RL formalism, deep RL practice tends to blur the line a fair bit—for instance, we frequently set up algorithms to optimize the undiscounted return, but use discount factors in estimating value functions.

could you provide an example and why the line is blurred?

**Comment by jachiam** [comment]
Two kinds of blurring:

1. We typically measure the "performance" of an RL algorithm by looking at the average episodic undiscounted sum of rewards, but we implement algorithms that use discount factors in value function learning, and increase probabilities of actions in proportion to advantage functions that use discount factors.

2. From the above, you might get the impression that we're measuring undiscounted return, but optimizing discounted return. The truth is, we aren't exactly optimizing for either! If we were truly optimizing for discounted return, there would be a discount factor included in the objective function for each state, corresponding to what timestep in a trajectory that state occurred. But, in typical implementations, we ignore that discount factor and weight each state's contribution equally.
