### ISSUE TITLE
installation fails due to mujoco

### ISSUE THREAD

**Issue by dan9thsense** [openai/spinningup#160]
Trying to follow the simplest method to get started from [here](https://spinningup.openai.com/en/latest/user/installation.html).  `pip install -e .` fails with multiple messages about MuJoCo.  Thinking that was OK, since MuJoCo is optional, I proceeded to try to run the `Check Your Install` line.  However, that fails with multiple things not installed, because the original installation dies after failing to install MuJoCo.  This is true both on Ubuntu 16.04 and 18.04.
`

**Comment by dan9thsense** [comment]
Resolved by removing line 23 from the setup.py file:
`'mujoco-py<2.1,>=2.0',`

If MuJoCo is optional, why is it included in the default setup.py file?

And, editorial comment, MuJoCo is very expensive, so unless it is truly optional, this is not really an open source project.

**Comment by bionicles** [comment]
same issue here. it would be good if mujoco install was off by default as it is a paid package

**Comment by ibrahiminfinite** [comment]
@dan9thsense @bionicles  
MuJoCo install, has been made optional with  PR #163.

**Comment by dan9thsense** [comment]
Thanks for the fast response!
