### ISSUE TITLE
how do you support "jagged" shapes with td3?

### ISSUE THREAD

**Issue by bionicles** [openai/spinningup#162]
our custom environment has a differently shaped observation/action space each episode. We want to use td3 algorithm and wonder how do you change the replay buffer and training to support jagged shapes? 

this might be handy for nlp or molecules/graphs where the number of variables is not fixed

**Comment by jachiam** [comment]
Hello @bionicles! Sorry for the late response.

It's not obvious to me how to best deal with obs / action spaces that change shape during each episode. I think there are some exotic kinds of neural networks that can handle variable input shapes, but I'm not familiar with that literature or how to implement them. [Graph Neural Networks](https://arxiv.org/pdf/1901.00596.pdf) might be what you are looking for.

Another thing you could try is using RNNs. Eg an RNN processes the input stream and returns a fixed-size output, or an RNN takes a fixed-size input and then autoregressively generates a sequence of output components.
