### ISSUE TITLE
How can I build the documentation on my local machine?

### ISSUE THREAD

**Issue by noklam** [openai/spinningup#166]
It would be nice if I can build local documentation as it allows me to go through the tutorials in offline situation.

**Comment by seungjaeryanlee** [comment]
Do you mean the documentation website `https://spinningup.openai.com/`?

This is created with [Sphinx](http://www.sphinx-doc.org/en/master/) with [Read the Docs (RTD)](https://pypi.org/project/sphinx-rtd-theme/) theme.

### 0. If you haven't already, clone this repository `openai/spinningup`:
```bash
git clone https://github.com/openai/spinningup
```

### 1. Download necessary packages
```bash
pip install sphinx sphinx_rtd_theme
```

### 2. Run Makefile in `docs` folder

All the documentation is located in `docs` folder, so navigate to it and run `make`.
```bash
cd docs/
./make.bat html   # Windows
make html         # Unix
```

### 3. View generated HTML files

HTML files should be generated in `docs/_build/html` folder. You can open `index.html` with your browser.

Or, you can also serve it in `localhost` using `python -m http.server` after navigating to that folder.

```
cd _build/html
python -m http.server
```

Go to `localhost:8000`.

**Comment by noklam** [comment]
@seungjaeryanlee  Thanks a lot!
