### ISSUE TITLE
Problem passing list of integers as command line argument

### ISSUE THREAD

**Issue by rayedbar** [openai/spinningup#17]
For some weird reason, when I spin up the walker environment passing in the sizes of the hidden layers as a list of integers as shown in the installation documentation:

> python -m spinup.run ppo --hid [32,32] --env Walker2d-v2 --exp_name installtest

I get the following error:

> zsh: no matches found: [32,32]

If I remove the square brackets it works. Can anyone demystify this for me please? Thank you!

**Comment by jachiam** [comment]
Square brackets are special characters in ZShell. To fix, either escape them or try the solution recommended here: http://kinopyo.com/en/blog/escape-square-bracket-by-default-in-zsh

Same as #6.
