### ISSUE TITLE
Query in VPG implementation (1_simple_pg.py)

### ISSUE THREAD

**Issue by hitesh11** [openai/spinningup#180]
Hi, this is just a clarification question:

In https://github.com/openai/spinningup/blob/2e0eff9bd019c317af908b72c056a33f14626602/spinup/examples/pg_math/1_simple_pg.py#L87

// the weight for each logprob(a|s) is R(tau)
   batch_weights += [ep_ret] * ep_len

Why do we multiply ep_len to [ep_ret] to calculate batch_weights? 

As per derivation on policy gradient (https://spinningup.openai.com/en/latest/spinningup/rl_intro3.html), the return is computed as expectation of sum of (logprob(a|s) * R(tau)) over trajectories. Why are we scaling R(tau) with ep_len in the implementation.

Thanks,
Hitesh

**Comment by arin-kwak** [comment]
We don't scale R(tau) with ep_len. `[ep_ret] * ep_len` results in `[ep_ret, ep_ret, ep_ret, ...]` whose length is `ep_len`.
Because R(tau) has the same value across a trajectory(episode), They(OpenAI) did this. I think.

**Comment by jachiam** [comment]
@yun-kwak has the correct answer. :)
