### ISSUE TITLE
why PPO is an on-policy algorithm?

### ISSUE THREAD

**Issue by zhengpw33** [openai/spinningup#183]
https://spinningup.openai.com/en/latest/algorithms/ppo.html
PPO is considered as an on-policy algorithm but it also uses the importance sampling item when updating the parameters of policy neural network.So is it an on-policy algorithm?

**Comment by jachiam** [comment]
It's considered "on-policy" because each update step solves an optimization problem that requires data from the most recent iteration of the policy. Using stale data is not generally recommended. (Although, to be fair, there is not a strong body of evidence to demonstrate that it would fail.)
