### ISSUE TITLE
Is there a good reason why often policy & value networks separated for Mujoco and shared for Atari ?

### ISSUE THREAD

**Issue by zuoxingdong** [openai/spinningup#19]
I am wondering if there is a rule of thumb for this. Maybe it is something related to the following reasonings ?

- Atari: shared parameters between policy and value networks. Because Atari uses pixel inputs, so the shared layers are regarded as a feature extractor. 

- Mujoco: separated parameters between policy and value networks. Because Mujoco uses raw configurations, and it has relatively shorter horizons, so by separating them out, it allowed value network to be trained with more gradient updates or independent learning rate to make it learning faster, as it is basically a regression task.

**Comment by jachiam** [comment]
I think it's basically right to think about it as a question of "do we need feature extraction or not," and when you do you want shared networks, and when the features are already good enough for the task you don't. But it's under-studied and I think it would be great if someone were to do a rigorous analysis (sadly this is my answer for a lot of questions in RL).
