### ISSUE TITLE
Example code fails for TensorFlow v2.0.0

### ISSUE THREAD

**Issue by ksaimanoj** [openai/spinningup#191]
The example for implementing the simplest policy gradient `spinup/examples/pg_math/1_simple_pg.py` fails for tensorflow v2.0.0 with the following message

```
Traceback (most recent call last):
  File "", line 124, in <module>
    train(env_name=args.env_name, render=args.render, lr=args.lr)
  File "", line 28, in train
    obs_ph = tf.placeholder(shape=(None, obs_dim), dtype=tf.float32)
AttributeError: module 'tensorflow' has no attribute 'placeholder'.
```

The placeholder has been removed from tensorflow v2.0.0

To replicate the issue, upgrade tensorflow to latest version (as of now 2.0.0)
and run the code in file `spinup/examples/pg_math/1_simple_pg.py`

**Comment by jachiam** [comment]
Tensorflow 2.0 is not supported by Spinning Up. This is reflected in the requirements in setup.py. Try with Tensorflow 1.15! :)
