### ISSUE TITLE
Tanh activation to SAC policy output not implemented

### ISSUE THREAD

**Issue by flfuch** [openai/spinningup#194]
The tanh "squashing function" mentioned in [the documentation of SAC](https://spinningup.openai.com/en/latest/algorithms/sac.html) is not implemented in [the SAC code](https://github.com/openai/spinningup/blob/master/spinup/algos/sac/sac.py).
`act_dim = env.action_space.shape[0]` is requested from the environment but never used after that.

**Comment by jachiam** [comment]
Squashing is applied in the `core.py` file, [here](https://github.com/openai/spinningup/blob/master/spinup/algos/sac/core.py#L73).

**Comment by flfuch** [comment]
Thank you for the fast answer @jachiam 
Maybe it would be better to remove the unused  `act_limit = env.action_space.high[0]` then, since the squashing is always done to the range (-1,1) anyways. Got it confused with `act_dim` in the first comment, sorry about that.
