### ISSUE TITLE
module 'tensorflow._api.v2.train' has no attribute 'AdamOptimizer'

### ISSUE THREAD

**Issue by jdshaffer** [openai/spinningup#197]
Hello. Basic user here.
Been following your installation instructions via your "Spinning Up" documentation. But when I try the install test (python -m spinup.run ppo --hid "[32,32]" --env LunarLander-v2 --exp_name installtest --gamma 0.999) I get the following error:

module 'tensorflow._api.v2.train' has no attribute 'AdamOptimizer'

No idea how to solve this one.

**Comment by jdshaffer** [comment]
Never mind. My bad. Bad installation on my end. Sorry!

**Comment by jdshaffer** [comment]
User error on this end. Sorry!

**Comment by clmnlab** [comment]
I had the same errors..what kind of bad installation did you figure out?

**Comment by JakobThumm** [comment]
I commented a solution on a newer ticket: https://github.com/openai/spinningup/issues/333
