### ISSUE TITLE
SAC solving any of the robotics environments 

### ISSUE THREAD

**Issue by TomasMerva** [openai/spinningup#198]
Has anyone solved any of the robotics environments, especially the Fetch environments, using spinningup implementation of SAC? According to _Multi-Goal Reinforcement Learning: Challenging Robotics Environments and Request for Research_ [Plappert et al.] DDPG algorithm without HER can solve `FetchReach-v0`. I have tried that with SAC (SpinningUp implementation with modified parameters similar to the paper)  and has been unable to solve it. Thats why I would like to know, if the problem is in my code or somewhere else. Thank you in advance

![image](https://user-images.githubusercontent.com/19751317/69911774-ba941f80-1420-11ea-9306-380f28d99d40.png)

![Figure_1](https://user-images.githubusercontent.com/19751317/69911891-48bcd580-1422-11ea-9273-6400236455f5.png)

**Comment by ReturnCloud** [comment]
Have you tried to solve this environment with DDPG implemented in spinup ?

**Comment by TomasMerva** [comment]
I had a problem at my side, I was capable of solving it with SAC (spinup version) +HER eventually. I forgot to close my question.

**Comment by ReturnCloud** [comment]
May I ask about your hyper-parameters?

**Comment by ReturnCloud** [comment]
May I ask about you hyper-parameters of DDPG and HER?
By the way, DDPG itself can solve this environment.

**Comment by ReturnCloud** [comment]
May I ask about you hyper-parameters of SAC and HER?
By the way, DDPG itself can solve this environment and I wonder about SAC itself, as SAC should be better than DDPG.

**Comment by TomasMerva** [comment]
Here is my implementation for the environment created in ROS, although the RL part is the same as it was in case of OpenAI environments. https://github.com/TomasMerva/ROS_KUKA_env/blob/master/kuka_push/scripts/kuka_agent.py

**Comment by ReturnCloud** [comment]
Thank you. I found that sac-v1 (with a value function) may work better than sac-v2 in this environment.
