### ISSUE TITLE
Missing Infinitesimals

### ISSUE THREAD

**Issue by pranv** [openai/spinningup#2]
I noticed in many (maybe all?) places the `dx` of ` \int_x f(x) dx ` was missing. Is this by choice?

**Comment by machinaut** [comment]
Maybe!  It would be helpful to know a few specific examples or places in the documentation where this was surprising to you.

Some of the notational conventions common to the field might be new to folks coming from other backgrounds, so including a note explaining it might be beneficial.

**Comment by pranv** [comment]
Personally, it was not surprising. Dropping them makes everything look cleaner. But the integral many people would know would be of a particular form and this could be off-putting. 

If you do not think this is a problem per se, please delete the issue.

**Comment by jachiam** [comment]
This was just a matter of taste to make things look cleaner, but you were right to check. I might revisit this if more people feel uncomfortable---comfort for the reader is something I think is super important. Will mark this issue as resolved for now.
