### ISSUE TITLE
How to make a proper reward function?

### ISSUE THREAD

**Issue by asdfqwer2015** [openai/spinningup#205]
The doc includes some rl algs and formula derivation. But how to make a proper reward function for a rl task to leads an alg to a better performance or easier to be convergenced? And how to make a reward function to make rl task easier?
If labels are groundtruth for supervised tasks, should reward functions be 'groundtruth' for rl tasks?
Any tutorial or reference or rules?
Thanks.

**Comment by parvkpr** [comment]
Hey @asdfqwer2015 ,
Reward functions are highly dependent on the problem you are trying to solve. Most of the OpenAI environments have an inbuilt reward function which you can access by returning from env.step(action).
If you're referring to reward shaping or optimization for a particular problem, then that requires a longer discussion. 
you can check out this [link](https://humancompatible.ai/bibliography#reward-engineering) for reward engineering, it'll give you a basic idea.
Also, reward functions are not the ground truth for RL tasks particularly. Reward functions are task specific where your aim is to maximize the reward achieved. If you refer to optimal performance towards which you can "ground" your model, then the maximum possible reward over all episodes can serve as an indicator of convergence.

**Comment by asdfqwer2015** [comment]
Thanks for your reply. It's really helpful for me. I'll read the articles mentioned in the link you recommended.
:)
