### ISSUE TITLE
Could not make the old SAC work, thanks for the new one - it works!

### ISSUE THREAD

**Issue by lostmsu** [openai/spinningup#206]
This is not really an issue.

I've spent the last two days trying to debug a port of the previous version of SAC (e.g. https://github.com/openai/spinningup/blob/b6965d89f5b713f6ad2a5fbef8f4db4fe4013250/spinup/algos/sac/), and was not able to figure out why it did not work. The action output would simply slowly go down to all zeroes even when I added +0.1 to action before submitting it to the environment to debug so that -0.1 would be a "steady" point.

The last thing I checked was making my own trivial environment where the reward was simply `abs(observation - agent_action)`, and watching losses. I noticed, that `q1`, `q2`, and `v` losses were all going down, but no matter what I did `pi_loss` was going up.  Even when I just did `sess.run([pi_train_op], ...)`, it would stay put. `logp_pi` would wiggle around +20 for any input, which made absolutely no sense.

Accidentally saw the new version, and after a quick adaptation it works perfectly. Would be curious to know if the previous version actually contained a bug of some sort, that you know of?

Anyway, thanks for the updated version. Its code is cleaner (and works too!).

**Comment by jachiam** [comment]
Glad to hear the new one is working for you!

As far as I could tell, there wasn't a bug in the old version (it seemed to run fine on OpenAI Gym MuJoCo environments, and I ported it over to other research code on a few occasions without issue). So I'm not sure what could have previously been the issue off-hand. If you post a more detailed account of what was going wrong (eg, exact details of your code modification / run script), I might be able to help.

**Comment by lostmsu** [comment]
@jachiam, sure, if you are interested. The code would be in C#, but I have a saved graph for TensorBoard, which I added a few extra annotations to.
[actorCritic.zip](https://github.com/openai/spinningup/files/4141079/actorCritic.zip)

**Comment by jachiam** [comment]
Ah, if in C#, I probably would not be extremely useful for debugging (I have no C# experience at all). 

Since all's well that end's well, I'm going to close this issue now. Happy continued hacking! :)
