### ISSUE TITLE
Expected return equation opaqueness

### ISSUE THREAD

**Issue by yaroslavyaroslav** [openai/spinningup#235]
While reading the key concepts section I’d struggle to understand the expected return formula. The part with capital E on the screenshot. Is it unit matrix or is it something else? Unfortunately i haven’t found any description of this notation in that section. 
![053AA5AF-C354-4F32-B9D5-CAF33DCE3138](https://user-images.githubusercontent.com/16612247/76164678-cf8bf780-6161-11ea-90da-1db7bc6581e2.jpeg)

**Comment by jachiam** [comment]
It's standard notation for [expected value](https://en.wikipedia.org/wiki/Expected_value). Hope this helps!

**Comment by yaroslavyaroslav** [comment]
Yes it is, thank you. Am i right that T~П under the math expectation sign means that T have distribution П?
