### ISSUE TITLE
Probability notation opaqueness 

### ISSUE THREAD

**Issue by yaroslavyaroslav** [openai/spinningup#236]
I’m unfortunately can’t get it. What the dot stands for in Stochastic policy notation In the key concepts section? I get it that this is conditional probability notation as well, but i haven’t see dot In that place any time before. 
![5836B69A-8648-40EB-B3E8-EDB55C6F1794](https://user-images.githubusercontent.com/16612247/76168190-6070cc00-617e-11ea-8f26-1c971ebfbb76.jpeg)

**Comment by jachiam** [comment]
pi is a function of two variables, with pi(a_t | s_t) denoting the conditional probability of a_t given s_t. In this notation, pi(dot | s_t) is the function/distribution that arises when you plug s_t in, but when you haven't specified what a_t is. (Some additional discussion: https://math.stackexchange.com/questions/1286490/what-is-the-meaning-of-expressions-of-the-type-f-cdot-function-dot)

**Comment by yaroslavyaroslav** [comment]
Thank you that helped
