### ISSUE TITLE
Installation issue with Python 3.7

### ISSUE THREAD

**Issue by kumarankit0411** [openai/spinningup#24]
There is an issue installing tensorflow with python 3.7 as discussed [here](https://github.com/tensorflow/tensorflow/issues/20444)

I installed Anaconda with python 3.7(MacOS) and it gave me error:
```
Could not find a version that satisfies the requirement tensorflow>=1.8.0 (from spinup==0.1.1) (from versions: )
No matching distribution found for tensorflow>=1.8.0 (from spinup==0.1.1)
```
The way I resolved it is by changing the version of python in Anaconda to 3.6 using this command:
`conda install python=3.6`

I understand there is a solution to this issue [here](https://github.com/tensorflow/tensorflow/issues/20444) but since spinningup is focused on helping beginners get started, I suppose the readme should aware users to install Anaconda with python 3.6 till the bug disappears in python 3.7.

**Comment by yanshen0** [comment]
I am using python3.7. Even after installing tensorflow 1.12 from the wheel, I still get the same error message when installing spinning up.

**Comment by kumarankit0411** [comment]
@yanshen0 If you have installed tensorflow manually, then you need to remove tensorflow from the list in setup.py file in the repo.

**Comment by jachiam** [comment]
Thanks for raising this! I've included a note about this issue [on the installation page](https://spinningup.openai.com/en/latest/user/installation.html).
