### ISSUE TITLE
R(Tau) does depend on theta in policy gradient derivation

### ISSUE THREAD

**Issue by ghost** [openai/spinningup#260]
I believe this is a mistake under Part 3: Intro to Policy Optimization, Deriving the Simplest Policy Gradient. R(Tau) depends on Tau, which depends on Pi, which depends on Theta. 

"4. Gradients of Environment Functions. The environment has no dependence on \theta, so gradients of \rho_0(s_0), P(s_{t+1}|s_t, a_t), and R(\tau) are zero."

**Comment by 1191000606** [comment]
I also find this problem, do you know how to fix the derivation or explain it
