### ISSUE TITLE
Why passing a lambda function of making the environment to the algorithm?

### ISSUE THREAD

**Issue by yd-yin** [openai/spinningup#270]
Take `ppo` as an example, `ppo(lambda: gym.make('my_env'), ...)` and inside the `ppo` function, call `env_fn()` to make the environment.

Can I change the definition of the function and first make the environment outside the `ppo` algo and pass the env directly? which means
```python
def ppo(env, ...)
    # eliminate this line: env = env_fn()
env = gym.make('my_env')
ppo(env, ...)
```

**Comment by krishpop** [comment]
the recommended way of dealing with this is to pass in a custom environment constructor/factory, since mpi needs to be able to spawn multiple envs in parallel (not just the one you pass into the alg constructor). See this related issue: #142

**Comment by yd-yin** [comment]
Thanks for the response
Got it
