### ISSUE TITLE
Issue running on macOS.

### ISSUE THREAD

**Issue by SomTambe** [openai/spinningup#307]
I have installed everything on macOS as per the guide, and everything seems to run perfectly. I trained the first example, and it trained successfully.
Finally, when I tried to visualize it, it gives me an error about OpenGL not being installed on macOS.

This is not very surprising as Apple deprecated OpenGL on macOS after making Metal the default framework.

Is there any solution to this? I tried googling and found one comprehensive guide ([this](https://giovanni.codes/opengl-setup-in-macos/)) which is very messy. 

If anyone has tried Spinning Up on macOS after 2018, could you elaborate on how did you make it work? Any kind of help would be awesome 😄 !

**Comment by monoclecat** [comment]
I've had the same issue and found a solution [here](https://github.com/openai/gym/issues/2101#issuecomment-730513761). Does the same work for you?

**Comment by SomTambe** [comment]
Hey @monoclecat , thanks for helping me out with the gym!
I changed my machine and I wouldn't be needing it anymore, but so nice of you to help me out!
