### ISSUE TITLE
Failed building wheel for box2d-py [solved]

### ISSUE THREAD

**Issue by dingran** [openai/spinningup#32]
I'm on MacOS with Anaconda

Initially had error `Failed building wheel for box2d-py`

Solution was to `brew install swig`

**Comment by jachiam** [comment]
@dingran, could you give more specific information about your system and Python environment?

@pzhokhov, who maintains Gym; any idea what happened?

**Comment by kumarankit0411** [comment]
@jachiam This happened with me too on MacBook Air 2015 model running MacOS Sierra with Python version 3.6 in Anaconda. Solved with `brew install swig` just like @dingran

**Comment by jachiam** [comment]
Can you give a ful error log?

**Comment by kumarankit0411** [comment]
This is what I got.

```
Running setup.py install for box2d-py ... error
    Complete output from command /Users/ankitkrsingh/miniconda3/envs/spinningup/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-j5kexno9/box2d-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-mamy1ivh/install-record.txt --single-version-externally-managed --compile:
    Using setuptools (version 40.5.0).
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/Box2D
    copying library/Box2D/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/Box2D
    copying library/Box2D/Box2D.py -> build/lib.macosx-10.7-x86_64-3.6/Box2D
    creating build/lib.macosx-10.7-x86_64-3.6/Box2D/b2
    copying library/Box2D/b2/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/Box2D/b2
    running build_ext
    building 'Box2D._Box2D' extension
    swigging Box2D/Box2D.i to Box2D/Box2D_wrap.cpp
    swig -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library/Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D/Box2D_wrap.cpp Box2D/Box2D.i
    unable to execute 'swig': No such file or directory
    error: command 'swig' failed with exit status 1
  ----------------------------------------
Command "/Users/ankitkrsingh/miniconda3/envs/spinningup/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-j5kexno9/box2d-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-mamy1ivh/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-j5kexno9/box2d-py/
```

**Comment by jachiam** [comment]
Since this is solved I'm going to close it for now.

As for diagnosing what happened: when pip installing, pip first tries a [wheel](https://packaging.python.org/tutorials/installing-packages/#source-distributions-vs-wheels) if one is available and compatible with your system, and if that fails, it tries to build from source. In order to install Box2d from source, you need to have swig installed. So for whatever reason (don't know why) your systems were incompatible with the pre-built wheel, defaulted to building Box2d from source, and then failed when they couldn't find swig---but installing swig fixed that!

Glad this worked out.

**Comment by pzhokhov** [comment]
@jachiam I think your analysis is correct. As for why the binary wheel was not found - looks like we have box2d-py wheels build for osx 10.13 (which means that they should work with osx versions 10.13+); and sierra is 10.12. I'll look into releasing binary versions of box2d-py for older version of osx.

**Comment by tokarev-i-v** [comment]
on Windows conda: conda install -c anaconda swig

**Comment by SolowomanYudachi** [comment]
> on Windows conda: conda install -c anaconda swig

I tried installing swig from anaconda, but the issue persists. It seems like the installation process did not find the swig after all, even though the anaconda is reporting functioning and configured correctly.

**Comment by jschultz299** [comment]
This [post](https://stackoverflow.com/questions/63972113/big-sur-clang-invalid-version-error-due-to-macosx-deployment-target) solved it for me.

**Comment by nishantb06** [comment]
```
error: command 'swig' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for box2d-py
  error: subprocess-exited-with-error
  
  × Running setup.py install for box2d-py did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Using setuptools (version 61.2.0).
      running install
      /Users/nishantbhansali/opt/miniconda3/envs/lightning-bolts-dev/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-3.9
      creating build/lib.macosx-10.9-x86_64-3.9/Box2D
      copying library/Box2D/Box2D.py -> build/lib.macosx-10.9-x86_64-3.9/Box2D
      copying library/Box2D/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/Box2D
      creating build/lib.macosx-10.9-x86_64-3.9/Box2D/b2
      copying library/Box2D/b2/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/Box2D/b2
      running build_ext
      building 'Box2D._Box2D' extension
      swigging Box2D/Box2D.i to Box2D/Box2D_wrap.cpp
      swig -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library/Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D/Box2D_wrap.cpp Box2D/Box2D.i
      error: command 'swig' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> box2d-py
```
This was my error message - `brew install swig `solved this too

**Comment by GayathriRangu** [comment]
On windows execute the command: 
_**pip install swig**_
Then try the previous commands you were trying to install. In my case, it was pip install gym[box2d]. This worked for me:
**_Successfully built box2d-py
Installing collected packages: box2d-py
Successfully installed box2d-py-2.3.5_**

**Comment by Toufiq0101** [comment]
swig is installed but gym[box2d] installation still failed on windows

**Comment by paolotoll** [comment]
I have the same error on Win 11. I installed swig this way: pip install swig.

The errors:
      swig.exe -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library\Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D\Box2D_wrap.cpp Box2D\Box2D.i
      Traceback (most recent call last):
        File "C:\Users\paolo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
          return _run_code(code, main_globals, None,
        File "C:\Users\paolo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
          exec(code, run_globals)
        File "C:\Users\paolo\AppData\Local\Programs\Python\Python310\Scripts\swig.exe\__main__.py", line 4, in <module>
      ModuleNotFoundError: No module named 'swig'
      error: command 'C:\\Users\\paolo\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\swig.exe' failed with exit code 1

**Comment by Suyash-Kumbharkar** [comment]
I am facing similar problem on my Windows11. Anyone found the solution?

**Comment by will-stonebridge** [comment]
similar issue to paolo

**Comment by Coquelicots** [comment]
`pip install swig` doesn't fix the problem on Windows.
I installed SWIG with Chocolatey: `choco install swig -y`,
then ran: `pip install "gymnasium[box2d]"`, and it worked.

**Comment by absundr** [comment]
For anyone facing this issue on windows, if you previously installed swig using `pip install swig` you need to uninstall it from your venv `pip uninstall swig` then install it from the binaries or using `choco install swig`.

**Comment by dzvenkov** [comment]
thanks for the comments above, using choco instead of pip worked for me too
