### ISSUE TITLE
Cannot run the first example on Mac OS.

### ISSUE THREAD

**Issue by zhjmcjk** [openai/spinningup#34]
I am installing Spinning Up on Mac OS. I followed this [link](https://spinningup.openai.com/en/latest/user/installation.html#id8)
After this, to see if you’ve successfully installed Spinning Up, I tried running PPO in the LunarLander-v2 environment with
`python -m spinup.run ppo --hid "[32,32]" --env LunarLander-v2 --exp_name installtest --gamma 0.999`
Then an error pops up
![image](https://user-images.githubusercontent.com/31545030/48414710-691de180-e786-11e8-89d7-bda1abc6b25d.png)
![image](https://user-images.githubusercontent.com/31545030/48414720-6f13c280-e786-11e8-8a76-561bd9de9494.png)
![image](https://user-images.githubusercontent.com/31545030/48414729-74710d00-e786-11e8-9d85-9c9257e102b5.png)

I have no idea about this error. Can anyone give me help?

**Comment by kumarankit0411** [comment]
@zhjmcjk The error is related to the version of python. As discussed [here](https://stackoverflow.com/questions/38466523/python-how-to-handle-the-valueerror-unsupported-pickle-protocol-4-error), Pickle protocol version 4 is not supported in Python 2.7. What python version are you using?

**Comment by zhjmcjk** [comment]
> python



> @zhjmcjk The error is related to the version of python. As discussed [here](https://stackoverflow.com/questions/38466523/python-how-to-handle-the-valueerror-unsupported-pickle-protocol-4-error), Pickle protocol version 4 is not supported in Python 2.7. What python version are you using?

The python version I used is **Python 3.6.7**

**Comment by kumarankit0411** [comment]
@zhjmcjk Are you using Anaconda with the separate environment as described in official spinningup docs [here](https://spinningup.openai.com/en/latest/user/installation.html#installing-python)

**Comment by machinaut** [comment]
@zhjmcjk we see this error when the default python executable is `python2.7` instead of python3.

The library launches sub-processes which run the command `python ...` so your launched shells need to have python correctly configured for them.

If you are using `pyenv-virtualenv` you can set the python environment for the local directory with `pyenv local <myenvname>` -- conda has similar functionality.

A good way to test that this works as expected is: open up a new shell in your working directory and run the command `python -c "import spinup"` -- if that works, then you probably have it setup correctly.

**Comment by jachiam** [comment]
@zhjmcjk Duplicate issue to #13, recommend you try the solution given there. Leaving this open in case that doesn't work.

**Comment by zhjmcjk** [comment]
> @zhjmcjk Are you using Anaconda with the separate environment as described in official spinningup docs [here](https://spinningup.openai.com/en/latest/user/installation.html#installing-python)?

> Yes. I ignored these two commands:`conda create -n spinningup python=3.6` and `source activate spinningup`. I always used **pip** command. Do I have to install **Anaconda**? Are there any other ways to solve this problem?

**Comment by zhjmcjk** [comment]
> @zhjmcjk we see this error when the default python executable is `python2.7` instead of python3.
> 
> The library launches sub-processes which run the command `python ...` so your launched shells need to have python correctly configured for them.
> 
> If you are using `pyenv-virtualenv` you can set the python environment for the local directory with `pyenv local <myenvname>` -- conda has similar functionality.
> 
> A good way to test that this works as expected is: open up a new shell in your working directory and run the command `python -c "import spinup"` -- if that works, then you probably have it setup correctly.

>@machinaut. I run the example using this command: `python3 -m spinup.run ppo --hid "[32,32]" --env LunarLander-v2 --exp_name installtest --gamma 0.999`
I also run the commands `python -c "import spinup"` and `python3 -c "import spinup"` in my computer. the result is 
![image](https://user-images.githubusercontent.com/31545030/48455498-60fd8a80-e7f6-11e8-9601-edb7dabe4e9b.png)

**Comment by jachiam** [comment]
@zhjmcjk, have you tried the solution recommended [here?](https://github.com/openai/spinningup/issues/13#issuecomment-437653826)
