### ISSUE TITLE
GAE-Lambda advantage calculation

### ISSUE THREAD

**Issue by juroberttyb** [openai/spinningup#349]
Hi,
First, thanks for this great project, this really helps a lot in learning RL!

I am currently tracing vpg.py, and found that although advantages are computed using generalized advantage estimator (GAE), targets of value function V are computed with reward-to-go without lambda.

In the supplementary material of [this paper](https://arxiv.org/pdf/1804.02717.pdf), the statement "Updating the value function using the temporal difference computed with the λ-return results in the TD(λ) algorithm" seems to indicate that target of value function V is generated with λ-return.

I am wondering if this is designed to be like this on purpose, if so, I would really like to know why.

Again, thank you guys so much for making this project available.

**Comment by juroberttyb** [comment]
After I dig more into it, I think that training V with reward-to-go is an attempt to make it more accurate, since reward-to-go is a special case of λ-return when λ=1, which is an unbiased estimate.

Also, it seems for some reason the implementation in vpg.py has the assumption that actor pi should be updated with a low variance estimate of rewards while V need not, but data used to compute loss for pi and V are of the same size, I am still thinking about the reason why.

**Comment by shivanimall** [comment]
following

**Comment by juroberttyb** [comment]
I have now come to a conclusion that using reward-to-go or λ-return for targets of V is simply of choice, since both choices would move current V toward a correct V.

GAE is proposed in [this paper](https://arxiv.org/pdf/1506.02438.pdf), for those who is interested, the derivation of GAE is from equation9 to equation16, and it is irrelevant of how we train V as long as V moves toward the correct V.

Note: correct V is a V that given s_t returns E[r_t + g x r_(t+1) + g^2 x r_(t+2) + ...] when using actor pi for all state s, g: discount factor

If I mistaken something, please let me know, thanks a lot.
