### ISSUE TITLE
How can I find the code of DDPG, just like ddpg.py. I want to read the code for further understanding.

### ISSUE THREAD

**Issue by yuhe-Ray** [openai/spinningup#363]

**Comment by Alberto-Hache** [comment]
It's in this very repo:

Pytorch version: https://github.com/openai/spinningup/tree/master/spinup/algos/pytorch/ddpg
Tensorflow (1.X) version: https://github.com/openai/spinningup/tree/master/spinup/algos/tf1/ddpg

**Comment by Alberto-Hache** [comment]
Hey, @yuhe-Ray , if it's solved, please tag the issue as solved (there are currently sooo many...). :)

Thanks

**Comment by yuhe-Ray** [comment]
Thank you very much!!
