### ISSUE TITLE
[Question]: Mujoco-specific, not recommended to constraint action within valid bound ?

### ISSUE THREAD

**Issue by zuoxingdong** [openai/spinningup#38]
It seems the SpinningUp implementations do not constraint actions according to `env.observation_space.low` and `env.observation_space.high`. I guess it's even discouraged to do action clipping after sampling from learned Gaussian distribution and this might be specific to Mujoco environment where the reward function contains penalty to the magnitude of actions i.e. `'reward_ctrl'`, so it automatically penalize when the action is out of bounds [-1, 1].

**Comment by jachiam** [comment]
Correct, for the policy optimization algorithms. DDPG/TD3/SAC do action clipping, but they are justified in the context of the algorithms.
