### ISSUE TITLE
PPO: Rewards-to-Go in finish_path() confusion/potential issue

### ISSUE THREAD

**Issue by bentotten** [openai/spinningup#388]
Looking through the finish_path() function for PPO , I am confused why we are adding `last_val` to the rewards-to-go calculation, as this causes it to make a different rewards-to-go than expected ... 

Using a gamma of 0.99, 
Assuming we have a rewards buffer of
 [-1.0, -1.0, -1.0] , 
 
 I believe the rewards-to-go should then be 
 ~[-2.970, -1.99, -1]
 
 However when the last state value is added to this, the array stored into `ret_buff` is
 ~[-2.678, -1.659, -0.73]

Was there a reason for this differing rewards-to-go function or was this a bug? Did I miss something in the docs that explain a different rewards-to-go than what was outlined [here](https://spinningup.openai.com/en/latest/spinningup/rl_intro3.html?highlight=rewards-to-go#implementing-reward-to-go-policy-gradient)?

```
   def finish_path(self, last_val=0):
        path_slice = slice(self.path_start_idx, self.ptr)
        rews = np.append(self.rew_buf[path_slice], last_val)
        vals = np.append(self.val_buf[path_slice], last_val)
        
        # the next two lines implement GAE-Lambda advantage calculation
        deltas = rews[:-1] + self.gamma * vals[1:] - vals[:-1]
        self.adv_buf[path_slice] = core.discount_cumsum(deltas, self.gamma * self.lam)
        
        # the next line computes rewards-to-go, to be targets for the value function
        self.ret_buf[path_slice] = core.discount_cumsum(rews, self.gamma)[:-1]
        
        self.path_start_idx = self.ptr
```

Specifically `rews = np.append(self.rew_buf[path_slice], last_val)` and `self.ret_buf[path_slice] = core.discount_cumsum(rews, self.gamma)[:-1]`

Thanks!

**Comment by Alberto-Hache** [comment]
You can find the explanation in the original comments of the Joshua:

        The "last_val" argument should be 0 if the trajectory ended
        because the agent reached a terminal state (died), and otherwise
        should be V(s_T), the value function estimated for the last state.
        This allows us to bootstrap the reward-to-go calculation to account
        for timesteps beyond the arbitrary episode horizon (or epoch cutoff).

What this means is that, when you don't have a fully finished episode, your best estimate of the total rewards ahead are the sum of the actual ones you've tracked (stored in self.rew_buf) + an estimate of the future ones; this estimate is exactly what last_val is, since it's the result of the value function on your last (unfinished) state.

Hope it helps.

Alberto

**Comment by bentotten** [comment]
Hi Alberto, thank you for your reply - When the agent has reached a terminal state, and the last_val is 0, this does seem to correctly mask the unneeded rewards.

Unfortunately when an epoch is cut-off before the terminal step, and the last_state is not zero, it seems to cause the rewards-to-go to be different than they should be - I could be incorrect though, please let me know if my math is incorrect for the original comment.

**Comment by bentotten** [comment]
I see, thank you
