### ISSUE TITLE
Exercise 1.1: adding epsilon to std

### ISSUE THREAD

**Issue by lbertge** [openai/spinningup#43]
Hello,

the provided solution `spinup/exercises/problem_set_1_solutions/exercise1_1_soln.py` includes the following snippet of code:

`...((x-mu)/tf.exp(log_std)+EPS) ** 2...`

which I'm a little curious about. The test passes without including the term `EPS` in my own solution (so I figure it doesn't matter), but I don't seem to find any mention of this epsilon parameter in the docs, https://spinningup.openai.com/en/latest/spinningup/rl_intro.html#stochastic-policies. 

I'd like to know if there is any reasoning behind this term?

**Comment by unrealwill** [comment]
Hello, you seem to have missed some parenthesis. In the solution code it is : 
`(((x-mu)/(tf.exp(log_std)+EPS))**2`
The EPS is there to avoid a possible division by zero which may happen later in training.

**Comment by jachiam** [comment]
@unrealwill's answer is correct: the EPS is there for numerical stability, in case the denominator gets close to zero. I will probably add an explanation for this to the docs in the future.
