### ISSUE TITLE
MuJoCo alternatives?

### ISSUE THREAD

**Issue by fancyerii** [openai/spinningup#44]
The free licence is only 30 days. Can spinningup use any free or open source alternatives such as Bullet(https://github.com/bulletphysics/bullet3)?

**Comment by jachiam** [comment]
The bullet-based alternative would be Roboschool. See #35 for a detailed response.

**Comment by jachiam** [comment]
But also if it wasn't clear: basically yes! The only requirements for environments are that 1) they are registered with Gym and 2) that they have vector-valued observations. If they satisfy these, you can use the Spinning Up implementations with them.

**Comment by erwincoumans** [comment]
> The bullet-based alternative would be Roboschool. See #35 for a detailed response.

PyBullet is better maintained as Roboschool, and it has a wider variety of Gym environments. See the [PyBullet documentation](https://docs.google.com/document/u/1/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.2ye70wns7io3). Installation is simply 'pip install pybullet'.

**Comment by benstonezhang** [comment]
You can check my commit for using pybullet with spinup. Only several lines of code change.
https://github.com/benstonezhang/spinningup/commit/c632f36d0ce46039c3f32120111d467a29c086ac
