### ISSUE TITLE
shape error

### ISSUE THREAD

**Issue by tdr1991** [openai/spinningup#47]
Hi everyone,

When I use the ppo algorithm, environment set "AirRaid-v0", but I get a error:
ValueError: Shape must be rank 2 but is rank 4 for 'pi/multinomial/Multinomial' (op: 'Multinomial') with input shapes: [?,250,160,6], [].

**Comment by jachiam** [comment]
Spinning Up implementations aren't default-compatible with Atari environments (although they are compatible with Atari Ram environments---try "AirRaid-ram-v0").

**Comment by tdr1991** [comment]
It seems like the env.observation_space.shape only 1D, but now I have a custom environment, env.observation_space.shape is two-dimensional.
