### ISSUE TITLE
Silent bug in ppo implementation - rewards shifted

### ISSUE THREAD

**Issue by OliverRichter** [openai/spinningup#50]
Looking at the PPO code I noticed that in each buffer slot the reward _before_ the corresponding observation is stored instead of the reward after the observation (OpenAI baselines implementation as correct implementation reference here: https://github.com/openai/baselines/blob/master/baselines/ppo2/runner.py). This leads to a bug in the finish_path method, where deltas are calculated as 
deltas = rews[:-1] + self.gamma * vals[1:] - vals[:-1]
which translates to r_t-1 + gamma * v_t+1 - v_t, i.e., the rewards are shifted and the value function has to approximate the rewards-to-go from t-1 instead of the rewards-to-go from t. This bug is silent in most control problems (where rewards are dense), but still might hinder performance. Can you confirm that this is indeed a bug?
(Also I didn't took an as close look at the other algorithms yet, maybe the same bug is present there as well?)

**Comment by jachiam** [comment]
Fixed in the latest version!
