### ISSUE TITLE
no matches found: [32,32]

### ISSUE THREAD

**Issue by Davincb** [openai/spinningup#6]
I install according to the instructions and get: 

zsh: no matches found: [32,32]

**Comment by jachiam** [comment]
Can you be a bit more specific about what system you're using, what you tried, and what happened? Where in the process did installation fail? Logs would be great.

**Comment by NeymarL** [comment]
I have the same problem when checking the installation. I'm using macOS Mojave.
After running 
```
pip install -e .
```
it says 
```
Successfully installed atari-py-0.1.6 atomicwrites-1.2.1 attrs-18.2.0 box2d-py-2.3.5 cloudpickle-0.5.2 gym-0.10.9 joblib-0.13.0 more-itertools-4.3.0 mpi4py-3.0.0 pluggy-0.8.0 py-1.7.0 pytest-3.10.0 seaborn-0.8.1 spinup
```
But when running 
```
python -m spinup.run ppo --hid [32,32] --env Walker2d-v2 --exp_name installtest
```
I got the error: `zsh: no matches found: [32,32]`.

**Comment by jachiam** [comment]
Could you try running

`python -m spinup.run ppo --hid "[32,32]" --env Walker2d-v2 --exp_name installtest`

and seeing if that works?

**Comment by NeymarL** [comment]
It works, thank you.

**Comment by jachiam** [comment]
The issue appears to be that Z-Shell (zsh) interprets square brackets as meaning "check for a pattern" instead of just reading them as strings. Escaping the square brackets solves the problem. Tomorrow I'll decide on a revision for the docs.

**Comment by rcshubhadeep** [comment]
I found the same issue. I just escaped them. like so - 

python -m spinup.run ppo --hid \[32,32\] --env Walker2d-v2 --exp_name installtest

**Comment by Davincb** [comment]
I'm on mac High Sierra, and get the error at the final step of the installation after pip installing on the spinningup repo. When I test the install with the test script: 

python -m spinup.run ppo --hid [32,32] --env Walker2d-v2 --exp_name installtest

it returns: 

zsh: no matches found: [32,32].

Adding "" resolves this issue: 

python -m spinup.run ppo --hid "[32,32]" --env Walker2d-v2 --exp_name installtest

Thanks!

**Comment by kirkstrobeck** [comment]
Looks like this works `pip install openai"[datalib]"`

thanks to https://github.com/openai/spinningup/issues/6#issuecomment-437325294

**Comment by iimrx** [comment]
I have solved this by using: `pip install openai"[embeddings]"` and it worked!
