### ISSUE TITLE
some equations in The pdf doc of RL spinningup are wrong

### ISSUE THREAD

**Issue by zhihaocheng** [openai/spinningup#66]
Thank you very much for your resources that help people learn fast. But one thing I found is that some equations in the pdf doc is not the same as those on html. And some figures are lost. For example, 
![image](https://user-images.githubusercontent.com/37742226/49484939-d8fa2600-f873-11e8-9477-b6d96603234d.png)
![image](https://user-images.githubusercontent.com/37742226/49485003-1c549480-f874-11e8-93d3-8cd035e372a2.png)

**Comment by jachiam** [comment]
You are correct, but unfortunately I am not sure what, if anything I can actually do about this. It seems that some custom commands are getting ignored and I do not know why.

**Comment by machinaut** [comment]
Maybe we should take down the incorrect (improperly-rendered) documentation and leave a note referencing this bug and fixes welcome?

**Comment by KylinA1** [comment]
I notice the error comes from 
` \underE`
Could you please try
`\mathop{\mathbb{E}}` to set notation expectation  `E` to be a math operator and then you can apply the `\limits` to set subscript symbols to the bottom of` E`.

for example:
`$\mathop{\mathbb{E}}\limits_\tau\sim\pi$`

**Comment by KylinA1** [comment]
> You are correct, but unfortunately I am not sure what, if anything I can actually do about this. It seems that some custom commands are getting ignored and I do not know why.

I notice the error comes from
\underE
Could you please try
\mathop{\mathbb{E}} to set notation expectation E to be a math operator and then you can apply the \limits to set subscript symbols to the bottom of E.

for example:
$\mathop{\mathbb{E}}\limits_\tau\sim\pi$

**Comment by jachiam** [comment]
This has now been fixed!
