### ISSUE TITLE
Using ExperimentGrid error: --cpu more than 1 can lead to more algorithm runs

### ISSUE THREAD

**Issue by watchernyu** [openai/spinningup#72]
Code to reproduce the error:

```
from spinup.utils.run_utils import ExperimentGrid
from spinup import ppo
import tensorflow as tf

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('--cpu', type=int, default=4)
    parser.add_argument('--num_runs', type=int, default=1)
    args = parser.parse_args()

    eg = ExperimentGrid(name='ppo-bench')
    eg.add('env_name', 'CartPole-v0', '', True)
    eg.add('seed', [10*i for i in range(args.num_runs)])
    eg.add('epochs', 10)
    eg.add('steps_per_epoch', 4000)
    eg.add('ac_kwargs:hidden_sizes', [(32,)], 'hid')
    eg.run(ppo, num_cpu=args.cpu)
```
Note that --cpu is 4, and --num_runs (number of seeds) is 1.
Simply run this code, and you will find that it first logs:

 Variants, counting seeds:               1
 Variants, not counting seeds:           1

This is correct, since for each hyperparameter and the seed we only give one entry. but then the whole ppo algorithm actually gets run 4 times. You will see 4 different logs coming to std output together (if you also seed the environment, you will see 4 exactly same logs), but since we only have one variant here, I believe the program should only run one ppo instance? 
Many thanks!

**Comment by jachiam** [comment]
Super interesting---I believe you, but I can't duplicate the error. I copied and pasted your exact script and ran it, and it ran fine: one log to std for one run of the algo. Can you tell me exactly what you ran at the command line to get this result?

**Comment by watchernyu** [comment]
Hi! I did some more testing and have found that if I run it from terminal it actually works perfectly. The problem only happens when I run it from my PyCharm interface. 
I'm not sure why it's different when running from PyCharm versus running from terminal, when I run other things they all work the same. But I guess it might be just something wrong with my PyCharm paths...

Sorry for the trouble and thank you very much for the help!

**Comment by jachiam** [comment]
No trouble at all! And the fact that it behaves oddly in PyCharm is still super weird---not as high-priority to me as if it was broken from the terminal, but definitely a thing that I'm curious about, since it sounds like running from PyCharm would have been part of a great user experience for you. Let me know if you look into this more deeply and figure out what was wrong. If the fix turns out to be quite simple, I'll be happy to include it in the repo.

Best of luck in your RL studies!
