### ISSUE TITLE
Reason for training value and action heads separately?

### ISSUE THREAD

**Issue by taliesinb** [openai/spinningup#75]
More of a question of why things are done a certain way than an issue, forgive me if this is the wrong forum.

https://github.com/openai/spinningup/blob/8b92b8a6fb1de63de59be61cd7a9a6ab7304c283/spinup/algos/ppo/ppo.py#L233

We see first the action is updated `train_pi_iters` times (or until max KL reached) and then value head is updated `train_v_iters` times. Why are these done separately and not jointly? Especially if parameters are shared between the policy and value networks then training only one objective at a time for a significant number of steps would surely cause it to worsen at the other objective. Why not train jointly (until max KL reached, in which case then just train value head for the remaining steps)?

**Comment by jachiam** [comment]
Good and reasonable question.

The code was written pretty much solely to support the case where policy and value networks are separate (and thus can be optimized separately). This is standard in RL for the sorts of tasks Spinning Up is mostly aimed at: eg the MuJoCo robotics tasks, simple control tasks, or Atari RAM. 

For Atari with image observations, it's common to make the policy and value networks share convolutional and possibly LSTM layers. In this case, you would need a shared objective and joint training, which the Spinning Up code doesn't currently support. The right update rule for this will look a bit different in each algorithm.
