### ISSUE TITLE
Typo in proof

### ISSUE THREAD

**Issue by Jukamala** [openai/spinningup#83]
I think in the extra material (Proof for Using Q-Function in Policy Gradient Formula)

spinningup/docs/spinningup/extra_pg_proof2.rst

there is a small typo in the definition of R_t
It should be R(s_t' , a_t', s_t'+1) instead of R(s_t , a_t, s_t+1)

**Comment by sagnik-chatterjee** [comment]
can i take up this issue ?

**Comment by Jukamala** [comment]
Sure
