### ISSUE TITLE
Why use subtraction in trpo parameter updates

### ISSUE THREAD

**Issue by Mayy1994** [openai/spinningup#93]
```
def set_and_eval(step):
      sess.run(set_pi_params, feed_dict={v_ph: old_params **-** alpha * x * step})   #???? Why - 
      return mpi_avg(sess.run([d_kl, pi_loss], feed_dict=inputs))
```
The paper said it should be old parameter plus the alpha * x * step here, why subtraction?

We tested the subtraction, and the average epoch return of subtraction result is  very low.

**Comment by Mayy1994** [comment]
Sorry, we have found the reason.

**Comment by laurinpaech** [comment]
I'm came up with exactly the same question, could you please elaborate why this is done?
