### ISSUE TITLE
Re-training SAC agent

### ISSUE THREAD

**Issue by gerdga** [openai/spinningup#98]
Does anybody has a script running which loads a trained SAC agent and continues training? 
The replay buffer should be reloaded, too...

Thanks!

**Comment by quan-dao** [comment]
You can create a new replay buffer by first letting the agent act randomly in the environment, then replace the random policy by the policy agent has learned (in other word, let the actor take the wheel).

**Comment by jachiam** [comment]
Hi @gerdga! Sorry, but Spinning Up implementations currently do not support continuing training from a saved point. I recommend you try to hack it as a project, though!
